Fix keyboard shortcuts: Use correct player.state attribute
BUG FIX: Keyboard shortcuts were checking player.playback_state which
doesn't exist - should be player.state instead.

Error was:
  AttributeError: 'AudioPlayer' object has no attribute 'playback_state'

Fixed: Changed self.player.playback_state to self.player.state in
ui/widgets/player_widget.py:349

Now Space bar play/pause toggle works correctly.